platform :ios, '9.0'

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:disable_input_output_paths => true

target 'LgMainProject' do
  inhibit_all_warnings!
  use_frameworks!

   #中间层
   pod 'LgPublicService', :path => '../LgComponents/LgPublicService'	

   #公共组件
   pod 'LgUIKit', :path => '../LgComponents/LgUIKit'

   #SDK库
   pod 'LgFramework', :path => '../LgComponents/LgFramework'

end
