# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LgMainProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LgMainProject



#  pod 'LgModules', :path => '../LgComponents/LgModules'
   pod 'LgCommon', :path => '../LgComponents/LgCommon'





end
